# standard github workflow for maven project with java8
name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Set Build Version
        run: echo "BUILD_VERSION=1.2.0-${{ github.run_number }}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package -Drevision=${{ env.BUILD_VERSION }} --file pom.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: target/**/*.jar,target/**/*.zip